---
all:
  children:
    aks:
      hosts:
        aks-prod:
          kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
    linux:
      hosts:
        vm-prod-1:
          ansible_host: 10.0.1.10
          ansible_user: azizmaram
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
