all:
  children:
    linux:
      hosts:
        honeypot-vm-1:
          ansible_host: 4.211.106.71
          ansible_user: azizmaram
          ansible_ssh_private_key_file: /home/aziz/mini-projet/terraform/.terraform/ssh_key
        honeypot-vm-2:
          ansible_host: 4.178.56.203
          ansible_user: azizmaram
          ansible_ssh_private_key_file: /home/aziz/mini-projet/terraform/.terraform/ssh_key
