---
# =========================================
# Auth-Lib Role - Handlers
# =========================================

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart auth-lib
  ansible.builtin.systemd:
    name: "{{ auth_lib_service_name }}"
    state: restarted

- name: stop auth-lib
  ansible.builtin.systemd:
    name: "{{ auth_lib_service_name }}"
    state: stopped

- name: start auth-lib
  ansible.builtin.systemd:
    name: "{{ auth_lib_service_name }}"
    state: started

